# Generated by Django 4.0.3 on 2022-04-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enunciados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('enunciado', models.CharField(max_length=400)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=255)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enunciados.carreras')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enunciados.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_termino', models.DateTimeField(auto_now_add=True, null=True)),
                ('errores', models.IntegerField(null=True)),
                ('id_enunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enunciados.enunciados')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enunciados.usuarios')),
            ],
        ),
    ]
