# Generated by Django 4.0.4 on 2022-04-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enunciados', '0002_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
